### ISSUE TITLE
The script doesn't trigger a new round.

### ISSUE THREAD

**Issue by jobsturm** [Happening/RankingGame#1]
In the Happening group I am part of, the current round says that is should've ended 7 hours ago.

![image](https://cloud.githubusercontent.com/assets/11157209/7903229/9918c36c-07d5-11e5-8d0d-04c0857c56ce.png)

It would be cool if you could take a look into this! 

Thank!
- Job

**Comment by EmielM** [comment]
We were having intermittent problems with processing timer queues. Should be fixed!
