### ISSUE TITLE
Update repo

### ISSUE THREAD

**Issue by jabbink** [Happening/RankingGame#2]
It seems like this repo does not reflect the version running on your servers, as this code does, as far as I can see, not contain the option to pick a question and also the question `Who is the most well-connected?` (which I can clearly see inside one instance of this game) is nowhere to be found in [`util.common.coffee`](https://github.com/Happening/RankingGame/blob/master/util.common.coffee#L36).

**Comment by jabbink** [comment]
@Happening

**Comment by Zenkala** [comment]
Hey @jabbink,

Sorry for the delay. We've pushed the latest commits to github.

**Comment by jabbink** [comment]
Thanks.
