### ISSUE TITLE
First question from the array of questions cannot be selected

### ISSUE THREAD

**Issue by roelvz** [Happening/RankingGame#3]
When a new question needs to be selected, and someone picks the first one from the array (which is ["drinks the most alcohol", true]), then another (random?) question is chosen.

Most likely, this has something to do with the fact that it's the first question in the array.

**Comment by tuimz** [comment]
+1 we have the same issue in our group

**Comment by Roywcm** [comment]
+1

**Comment by EmielM** [comment]
Should be fixed!
